[project]
name = "scrapingbee-load-site-data-model-training"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "lxml>=6.1.0",
    "pandas>=3.0.2",
    "requests>=2.33.1",
    "scrapingbee>=2.0.2",
    "tenacity>=9.1.4",
]
